name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  ITCHIO_USERNAME: ${{ secrets.ITCHIO_USERNAME }}
  ITCHIO_GAME: ${{ secrets.ITCHIO_GAME }}

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Install 🧩
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default \
          && unzip butler.zip \
          && cp butler /usr/bin \
          && chmod +x /usr/bin/butler
      - name: Build 🔧
        run: |
          build.sh
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
